version: 0.1

phases:
  pre_build:
    commands:
      - echo "pre build"
      - chmod +x *.sh
      - ./decrypt.sh secrets.js
      - npm install --production
  build:
    commands:
      - echo "build"
      - npm run prep
      - npm test
      - npm run build
  post_build:
    commands:
      - echo "post build"
      - ./publish.sh
