version: 0.1

phases:
  pre_build:
    commands:
      - echo "pre build"
      - chmod +x *.sh
  build:
    commands:
      - echo "build"
      - ./decrypt.sh secrets.js.encrypted > secrets.js
      - ls -l secrets.js
      - npm install
      - npm run prep
      - npm test
      - npm run build
  post_build:
    commands:
      - echo "post build"
      - ./publish.sh
