version: 0.1
phases:
  pre_build:
    commands:
      - echo "pre build"
      - npm install
  build:
    commands:
      - echo "build"
      - npm run build
  post_build:
    commands:
      - echo "post buld"
artifacts:
  files: build/
  discard-paths: yes
